# Site settings
title: victor
SEOTitle: 小明哥的技术博客
header-img: img/home-bg.jpg
email: fengming19981221@163.com
description: "关于程序、设计以及架构 | 小明哥，Javaer ，Software Engineer"
keyword: "小明哥, mercyblitz, victor, 小明哥的技术博客"
url: "https://victorfengming.gitee.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

post:
  author: victor

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     p/1005055739661018
github_username:    victorfengming
twitter_username:   mercyblitz
qq_number:   510510280
#facebook_username:  mercyblitz
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: mercyblitz

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: TODO            # Format: UA-xxxxxx-xx
# ga_domain: TODO



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "大家好，我是小明哥"
sidebar-avatar: /img/avatar-mecyblitz.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true



# Friends
friends: [
    {
        title: "ttk",
        href: "https://ttk1907.gitee.io/"
    },
    {
        title: "yupeng",
        href: "https://zhengyupengzz.github.io/"
    },
    {
        title: "jiesang",
        href: "https://jiesangqaq.github.io"
    },
    {
        title: "yueyang",
        href: "https://1978413822.github.io/"
    },
    {
        title: "chenzan",
        href: "https://llzanz.github.io/"
    },
    {
        title: "haha",
        href: "https://caoyang7.github.io/"
    },
    {
        title: "rwj",
        href: "https://raoweijiapng.github.io/"
    }
]
